---
version: "3.9"

services:
  database:
    build:
      context: database
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: default
      POSTGRES_DB: default
    hostname: database
    restart: always
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - /pgdata

  nats:
    image: nats:2.9-alpine
    container_name: nats
    hostname: nats
    restart: always
    command:
      - "-js"
      - "-DVV"
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    networks:
      - saga
  nats-box:
    image: natsio/nats-box:latest
    container_name: nats-box
    hostname: nats-box
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - nats
    networks:
      - saga
networks:
  saga:
    driver: bridge
