[package]
name = "consumer_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.2.1"
actix-cors = "0.6.4"
actix-csrf = "0.7.0"
serde_json = "^1.0"
url = { version = "^2.1" }
env_logger = "0.10.0"
