[package]
name = "consumer_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4.3.0"
actix-cors = "0.6.1"
serde_json = "^1.0"
cloudevents-sdk = { version = "0.7.0",features = ["actix"] }
url = { version = "^2.1" }
env_logger = "0.10.0"
